// <auto-generated />
namespace IndividualAssignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class princonstructorsubmitno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(princonstructorsubmitno));
        
        string IMigrationMetadata.Id
        {
            get { return "201903172354154_prin constructor submit=no"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
